import {describe,expect,it} from "vitest";
import {roomPlacement,roomManualPlacement} from "../lib/mockup-v3/rooms/placement";
import {allowedFrameSize,type RoomDefinition} from "../lib/mockup-v3/rooms/schema";

const room:RoomDefinition={
  id:"cozy-living-01",
  image:{key:"rooms/cozy-living-01.png",width:1600,height:1000,origin:"ai-generated"},
  rights:{approved:true,commercialUse:true,notes:"Pilot only; generated by owner"},
  wall:{quad:[{x:200,y:100},{x:1400,y:100},{x:1400,y:700},{x:200,y:700}],widthCm:400,heightCm:200,scaleVerified:true},
  region:{id:"above-sofa",leftCm:100,topCm:20,widthCm:200,heightCm:130},
  light:{direction:"left",temperature:"warm"}
};
describe("Room Library pilot",()=>{
  it("allows 30x40 and 60x80 outer frames, rejects larger sizes",()=>{
    expect(allowedFrameSize({width:30,height:40})).toBe(true);
    expect(allowedFrameSize({width:60,height:80})).toBe(true);
    expect(allowedFrameSize({width:80,height:60})).toBe(true);
    expect(allowedFrameSize({width:90,height:120})).toBe(false);
  });
  it("projects a centred 60x80cm frame onto the known wall",()=>{
    const p=roomPlacement(room,{width:60,height:80});
    expect(p.ok).toBe(true);
    if(!p.ok)return;
    expect(p.targetQuad[0].x).toBeCloseTo(710,5);
    expect(p.targetQuad[0].y).toBeCloseTo(235,5);
    expect(p.targetQuad[2].x).toBeCloseTo(890,5);
    expect(p.targetQuad[2].y).toBeCloseTo(475,5);
  });
  it("rejects unverified metric scale",()=>{
    const p=roomPlacement({...room,wall:{...room.wall,scaleVerified:false}},{width:30,height:40});
    expect(p).toEqual({ok:false,error:"WALL_SCALE_UNVERIFIED"});
  });
  it("rejects a frame that cannot fit the placement region",()=>{
    const p=roomPlacement({...room,region:{id:"narrow",leftCm:150,topCm:30,widthCm:35,heightCm:45}},{width:60,height:80});
    expect(p).toEqual({ok:false,error:"ART_TOO_LARGE_FOR_REGION"});
  });
  it("provides the existing pipeline with a manual target and exact physical width",()=>{
    const p=roomManualPlacement(room,{width:30,height:40});
    expect(p.ok).toBe(true);
    if(!p.ok)return;
    expect(p.options.physicalWidthM).toBe(0.3);
    expect(p.options.placement).toBe("free-wall");
    expect(p.manual.targetQuad).toHaveLength(4);
  });
  it("rejects rooms without commercial-use clearance",()=>{
    const p=roomPlacement({...room,rights:{approved:false,commercialUse:false,notes:""}},{width:30,height:40});
    expect(p).toEqual({ok:false,error:"ROOM_RIGHTS_NOT_APPROVED"});
  });
});
