const IMAGE=/\.(jpe?g|png|webp|heic|heif|tiff?|gif|avif|bmp|raw|dng|cr2|nef|arw|psd)$/i;
/** Images allowed in git: tiny synthetic goldens/previews generated by the test-suite, and public app assets. */
const ALLOW=[/^tests\/goldens\//,/^docs\/phase3-previews\//,/^public\//,/^app\/.*\.(png|ico|jpg|svg)$/];
export function findForbiddenTracked(files:string[]):string[]{
  return files.filter((f)=>IMAGE.test(f)&&!ALLOW.some((a)=>a.test(f)));
}
